language: python
python:
    - "2.7"

env:
    - PLATFORMIO_CI_SRC=path/to/test/file.c
    - PLATFORMIO_CI_SRC=examples/file.ino
    - PLATFORMIO_CI_SRC=path/to/test/directory

install:
    - pip install -U platformio

script:
    - platformio ci --board=<ID_1> --board=<ID_2> --board=<ID_N>